import {isMultiscale,readMultiscaleBundle} from './multiscale-input.js';
export function mountMultiscaleUi({after,scope,revision}){
 const $=id=>document.getElementById(id),panel=document.createElement('div');panel.className='fields two';panel.id='multiscale-fields';let inputs=Object.create(null),sequence=0,loading=false;
 function select(id,title,choices){const label=document.createElement('label');label.textContent=title;const input=document.createElement('select');input.id=id;for(const [value,text]of choices){const option=document.createElement('option');option.value=value;option.textContent=text;input.append(option);}label.append(input);panel.append(label);return input;}
 const fine=select('multiscale-fine','Fine resolution',[['tract','Census tract'],['bg','Block group']]),coarse=select('multiscale-coarse','Coarse resolution',[['county','County'],['tract','Census tract']]);
 for(const [id,title,value,min,max,step]of[['multiscale-alpha','Coarse move probability',.3,0,1,.01],['multiscale-target','Target coarse acceptance',.3,0,1,.01],['multiscale-interval','Adapt every N steps',50,1,100000,1],['multiscale-gamma','Initial adaptation rate',.1,0,1,.01],['multiscale-factor','Coarse tolerance multiplier',3,1,10,.1]]){const label=document.createElement('label');label.textContent=title;const input=document.createElement('input');Object.assign(input,{id,type:'number',value,min,max,step,required:true});label.append(input);panel.append(label);}
 const label=document.createElement('label');label.textContent='Block-group graph and map JSON files';const files=document.createElement('input');files.id='multiscale-files';files.type='file';files.multiple=true;files.accept='.json';label.append(files);panel.append(label);
 const help=document.createElement('p');help.className='help';help.textContent='Tract→county uses the prepared state graph. Block-group runs require an explicit bundle with graph, physical boundary edges and GeoJSON for every selected state. Inputs must match tract population and adjacency. Sampling and ranking use unweighted fine adjacency. Imported geometry and source descriptions are user-supplied.';panel.append(help);
 const status=document.createElement('p');status.id='multiscale-status';status.setAttribute('role','status');panel.append(status);
 const render=()=>{status.textContent=Object.values(inputs).map(b=>`${b.graph.state} ${b.graph.year} · ${b.graph.geoids.length.toLocaleString()} block groups · ${b.source_label}`).join('; ')||'No block-group bundles loaded.';};
 const clear=document.createElement('button');clear.type='button';clear.textContent='Clear block-group inputs';clear.onclick=()=>{sequence++;loading=false;inputs=Object.create(null);render();};panel.append(clear);
 files.onchange=async()=>{const chosen=[...files.files],expected=++sequence,rev=revision();if(!chosen.length)return;loading=true;status.textContent='Checking block-group inputs…';try{if(chosen.length>50||chosen.reduce((n,f)=>n+f.size,0)>25*1024*1024)throw new Error('Select at most fifty bundles totaling at most 25 MiB.');const next=Object.create(null);for(const f of chosen){const b=await readMultiscaleBundle(f);if(next[b.graph.state])throw new Error('Select one bundle per state.');next[b.graph.state]=b;}if(expected!==sequence||rev!==revision())throw new Error('Project changed while reading inputs.');inputs={...inputs,...next};render();}catch(e){if(expected===sequence)status.textContent=e.message;}finally{if(expected===sequence){loading=false;files.value='';}}};
 after.after(panel);render();
 const api={refresh(){const active=isMultiscale($('search').value),adaptive=$('search').value==='multiscale-adaptive';panel.hidden=!active;for(const e of panel.querySelectorAll('input,select'))e.disabled=!active;if(fine.value==='tract')coarse.value='county';for(const o of coarse.options)o.disabled=fine.value==='tract'&&o.value==='tract';files.disabled=!active||fine.value!=='bg';for(const id of['multiscale-target','multiscale-interval','multiscale-gamma','multiscale-factor']){$(id).disabled=!active||!adaptive;$(id).parentElement.hidden=!adaptive;}if(active){$('weights').value='geographic';$('weights').disabled=true;$('seeds-field').hidden=true;$('seeds').value=1;$('steps').min=0;$('steps').disabled=false;$('search-description').textContent='Initialize on weighted geographic tract boundaries, then propose unweighted Wilson ReCom moves at fine or coarse resolution. Rebalance coarse moves and rank retained fine plans by unweighted cut. Population and connectivity outcomes are shown explicitly; this search does not prove optimality.';for(const id of['character-fields','partisan-fields'])if($(id))$(id).hidden=true;}},config(){if(loading)throw new Error('Wait for block-group inputs to finish loading.');return {fine_level:fine.value,coarse_level:coarse.value,total_steps:Number($('steps').value),alpha:Number($('multiscale-alpha').value),percentile:Number($('percentile').value)/100,adaptive:$('search').value==='multiscale-adaptive'?{target_accept:Number($('multiscale-target').value),adapt_interval:Number($('multiscale-interval').value),gamma_0:Number($('multiscale-gamma').value),coarse_tol_factor:Number($('multiscale-factor').value)}:null,inputs:fine.value==='bg'?Object.fromEntries(scope().states.map(code=>[code,inputs[code]])): {}};},restore(c){sequence++;loading=false;inputs=structuredClone(c.multiscale?.inputs??{});fine.value=c.multiscale?.fine_level??'tract';coarse.value=c.multiscale?.coarse_level??'county';$('multiscale-alpha').value=c.multiscale?.alpha??.3;const a=c.multiscale?.adaptive;for(const[id,value]of[['multiscale-target',a?.target_accept??.3],['multiscale-interval',a?.adapt_interval??50],['multiscale-gamma',a?.gamma_0??.1],['multiscale-factor',a?.coarse_tol_factor??3]])$(id).value=value;render();api.refresh();}};
 fine.onchange=()=>api.refresh();return api;
}
