#!/usr/bin/env python3
"""
Generate static dashboard HTML with district data baked in.

This script reads the dashboard template and injects district city data
for all states, creating a fully static HTML file.

Usage:
    python scripts/web/generate_dashboard.py --year 2020 --version v1
"""

import argparse
import json
import os
import sys
from pathlib import Path
import pandas as pd


def load_district_data(state_dir):
    """Load district cities data for a state."""
    cities_file = state_dir / 'district_cities.csv'
    if not cities_file.exists():
        return None

    try:
        df = pd.read_csv(cities_file)

        # Build district data array
        districts = []
        for _, row in df.iterrows():
            district_num = str(row['district'])
            city_name = row['largest_city']

            # Handle NaN or numeric values
            if pd.isna(city_name) or not isinstance(city_name, str):
                city_name = f"District {district_num}"

            # Create filename-safe version of city name
            city_filename = city_name.lower()
            city_filename = city_filename.replace(' ', '_')
            city_filename = city_filename.replace('.', '')
            city_filename = city_filename.replace(',', '')
            city_filename = city_filename.replace("'", '')

            districts.append({
                'num': district_num,
                'city': city_name,
                'filename': city_filename
            })

        return districts
    except Exception as e:
        print(f"  Warning: Error loading district data for {state_dir.name}: {e}")
        return None


def generate_dashboard(year, version, output_dir=None, template_file=None):
    """Generate static dashboard HTML."""

    # Default paths
    if template_file is None:
        template_file = Path('web/dashboard.html')

    if output_dir is None:
        output_dir = Path(f'outputs/us_{year}_{version}')
    else:
        output_dir = Path(output_dir)

    # Check paths
    if not template_file.exists():
        print(f"ERROR: Template file not found: {template_file}")
        return 1

    if not output_dir.exists():
        print(f"ERROR: Output directory not found: {output_dir}")
        return 1

    print(f"Generating dashboard for {year} Census, version {version}...")
    print(f"  Template: {template_file}")
    print(f"  Output: {output_dir}")

    # Read template
    with open(template_file, 'r', encoding='utf-8') as f:
        template_html = f.read()

    # Build DISTRICT_DATA object
    district_data = {}
    states_dir = output_dir / 'states'

    if not states_dir.exists():
        print(f"  Warning: States directory not found: {states_dir}")
        print("  Dashboard will be generated without district data")
    else:
        print(f"\n  Loading district data from states...")
        loaded = 0
        skipped = 0

        for state_dir in sorted(states_dir.iterdir()):
            if not state_dir.is_dir():
                continue

            state_name = state_dir.name
            districts = load_district_data(state_dir)

            if districts:
                district_data[state_name] = districts
                loaded += 1
            else:
                skipped += 1

        print(f"  Loaded district data for {loaded} states")
        if skipped > 0:
            print(f"  Skipped {skipped} states (no district_cities.csv)")

    # Generate JavaScript variable
    district_data_js = f"const DISTRICT_DATA = {json.dumps(district_data, indent=8)};"

    # Inject into template
    # Find the line with the comment about DISTRICT_DATA
    injection_comment = "// Note: DISTRICT_DATA will be injected here during deployment"

    if injection_comment in template_html:
        # Replace the comment with the actual data
        dashboard_html = template_html.replace(
            injection_comment,
            f"// District data generated by generate_dashboard.py\n        {district_data_js}"
        )
    else:
        print("  Warning: Injection comment not found in template, appending to script")
        # Fallback: inject before closing </script> tag
        dashboard_html = template_html.replace(
            "    </script>",
            f"\n        // District data generated by generate_dashboard.py\n        {district_data_js}\n    </script>"
        )

    # Write output
    output_file = output_dir / 'index.html'
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(dashboard_html)

    print(f"\nDashboard generated: {output_file}")
    print(f"  File size: {len(dashboard_html):,} bytes")
    print(f"  District data: {len(district_data)} states")

    return 0


def main():
    parser = argparse.ArgumentParser(
        description='Generate static dashboard HTML with district data'
    )
    parser.add_argument('--year', type=str, required=True,
                       choices=['2010', '2020', '2030', '2040'],
                       help='Census year')
    parser.add_argument('--version', type=str, required=True,
                       help='Version (e.g., v1, v2)')
    parser.add_argument('--output-dir', type=str,
                       help='Output directory (default: outputs/us_YEAR_VERSION)')
    parser.add_argument('--template', type=str,
                       help='Dashboard template file (default: web/dashboard.html)')

    args = parser.parse_args()

    return generate_dashboard(
        args.year,
        args.version,
        args.output_dir,
        args.template
    )


if __name__ == '__main__':
    sys.exit(main())
