import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {runInNewContext} from 'node:vm';
const ui=await fs.readFile('web/lab/lab.js','utf8');
const source=ui.slice(ui.indexOf('function renderSmcDiagnostics('),ui.indexOf('function renderMergeHistory('));
assert.ok(source.length>0);assert.ok(!/innerHTML|outerHTML|insertAdjacentHTML|eval\s*\(/.test(source));
const nodes=new Map();
const element=tag=>({tag,children:[],append(...children){this.children.push(...children);},replaceChildren(){this.children=[];},after(child){nodes.set(child.id,child);}});
nodes.set('root-constraint-detail',element('p'));
const sandbox={$:id=>nodes.get(id),document:{createElement:element},number:String};
runInNewContext(source,sandbox);
const evidence={method:'smc-percentile',selected_particle:99,ranked_particles:Array.from({length:100},(_,particle)=>({particle,edge_cut:particle,weight:0.01})),ess_trace:Array(100).fill(50),resample_rounds:[1,3]};
sandbox.renderSmcDiagnostics(evidence);
const panel=nodes.get('smc-diagnostics');assert.equal(panel.hidden,false);
const tables=panel.children.filter(child=>child.tag==='table');
assert.equal(tables[0].children.length,52);assert.equal(tables[1].children.length,51);
assert.equal(tables[0].children.at(-1).children[0].textContent,'99');
assert.equal(tables[0].children.at(-1).children[3].textContent,'Selected');
sandbox.renderSmcDiagnostics({method:'flow-construction'});
assert.equal(panel.hidden,true);assert.equal(panel.children.length,0);
console.log('SMC display: bounded particle/stage tables, selected particle retained beyond preview limit, text-only rendering and clearing passed.');
