import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {instantiateEngine} from '../../web/lab/wasm-engine.js';
import {WasmCatalog} from '../../web/lab/wasm-catalog.js';
import {createLabProject,validateLabProject} from '../../web/lab/laboratory-project.js';
import {validateMultiscaleBundle} from '../../web/lab/multiscale-input.js';
const root=process.argv[2]||'dist/wasm-character',original=JSON.parse(await fs.readFile(path.join(root,'catalog.json'),'utf8'));
const engine=await instantiateEngine(await fs.readFile('target/wasm32-unknown-unknown/release/bisect_wasm.wasm'));
const manifest=structuredClone(original),assets=new Map(),bundles={};let runs=0,native=0,restored=0,maps=0,rejected=0,balanceMisses=0,disconnected=0,lastRequest,lastResult;
manifest.catalog.search_compatibility['standard-bisect'].push('multiscale','multiscale-adaptive');
function asset(value){const bytes=Buffer.from(JSON.stringify(value)),hash=createHash('sha256').update(bytes).digest('hex'),ref=`assets/${hash}.json`;assets.set(ref,bytes);manifest.assets[ref]=hash;return ref;}
const base=JSON.parse(await fs.readFile('target/multiscale-fixtures/request-0-0.json','utf8')).input.request.graph;
const polygon=i=>({type:'Polygon',coordinates:[[[-86+i/1000,32],[-86+i/1000+.0005,32],[-86+i/1000+.0005,32.0005],[-86+i/1000,32.0005],[-86+i/1000,32]]]});
for(const [code,fips]of[['AL','01'],['AK','02'],['RI','44']]){
 const g=structuredClone(base);g.state=code;g.geoids=g.geoids.map(id=>fips+id.slice(2));const geometry={type:'FeatureCollection',features:g.geoids.map((id,i)=>({type:'Feature',properties:{geoid:id},geometry:polygon(i)}))};
 const graphRef=asset(g),geometryRef=asset(geometry);manifest.graphs[`${code}:2020`]={graph_ref:graphRef,native_graph_sha256:createHash('sha256').update(JSON.stringify(g)).digest('hex')};manifest.geometries[`${code}:2020`]=geometryRef;
 manifest.catalog.states=manifest.catalog.states.filter(s=>s.code!==code);manifest.catalog.states.push({code,name:`SYNTHETIC ${code}`,years:[{year:'2020',districts:{congressional:3,house:3,senate:3}}]});
 const bg={schema_version:'bisect-block-group-graph-v1',state:code,year:'2020',geoids:g.geoids.flatMap(id=>[id+'1',id+'2']),population:Array(g.geoids.length*2).fill(50),adjacency:Array.from({length:g.geoids.length*2},(_,i)=>[i^1,...g.adjacency[Math.floor(i/2)].map(j=>j*2+i%2)].sort((a,b)=>a-b))};
 bundles[code]=validateMultiscaleBundle({schema_version:'bisect-multiscale-input-v1',source_label:`SYNTHETIC ${code} fine graph/map`,graph:bg,boundary_edges:bg.adjacency.flatMap((ns,i)=>ns.filter(j=>j>i).map(j=>[i,j,100])),geometry:{type:'FeatureCollection',features:bg.geoids.map((id,i)=>({type:'Feature',properties:{geoid:id},geometry:polygon(i)}))}},g);
 await fs.writeFile(`target/${code}-SYNTHETIC-multiscale.json`,JSON.stringify(bundles[code]));
}
const fetcher=async ref=>{const bytes=assets.get(ref)||await fs.readFile(path.join(root,ref));return{ok:true,arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.length)};};
class Worker{postMessage(m){setImmediate(()=>{if(this.terminated)return;try{if(m.type==='initialize')this.onmessage({data:{type:'ready'}});else{runs++;lastRequest=m.request;lastResult=engine.execute(m.request);this.onmessage({data:{type:'result',id:m.id,result:lastResult}});}}catch(e){this.onmessage({data:{type:'error',id:m.id,error:e.message}});}});}terminate(){this.terminated=true;}}
const config=(fine,coarse,adaptive,steps,states=['AL'])=>({name:'SYNTHETIC multiscale laboratory test',mode:states.length>1?'national':'state',states,year:'2020',chamber:'congressional',districts:states.length>1?null:3,structure:'standard-bisect',search:adaptive?'multiscale-adaptive':'multiscale',weights:'geographic',seed:'18446744073709551615',seeds:1,steps,percentile:0,alpha_county:0,balance_tolerance:5,area_swing:1.1,iterations:10,timeout_seconds:60,multiscale:{fine_level:fine,coarse_level:coarse,total_steps:steps,alpha:.3,percentile:0,adaptive:adaptive?{target_accept:.3,adapt_interval:5,gamma_0:.1,coarse_tol_factor:3}:null,inputs:fine==='bg'?Object.fromEntries(states.map(code=>[code,structuredClone(bundles[code])])):{}}});
async function check(c,activeManifest=manifest,activeFetcher=fetcher){const lab=new WasmCatalog(activeManifest,activeFetcher,()=>new Worker()),job=lab.submit(c);while(lab.active)await new Promise(r=>setTimeout(r,5));assert.equal(lab.jobs.get(job.id).status,'completed',JSON.stringify(lab.jobs.get(job.id).states));
 const requestPath='target/multiscale-project-native-request.json';await fs.writeFile(requestPath,JSON.stringify(lastRequest));const ref=spawnSync('target/release/examples/execute_tool_request.exe',[requestPath],{encoding:'utf8',maxBuffer:32*1024*1024});assert.equal(ref.status,0,ref.stderr);assert.deepEqual(JSON.parse(ref.stdout),lastResult);native++;
 const project=await createLabProject(lab,job.id),before=runs,open=new WasmCatalog(activeManifest,activeFetcher,()=>{throw new Error('Open must not execute the engine.');}),result=await open.restoreProject(project);assert.equal(runs,before);restored++;const jobsAfterOpen=open.jobs.size;
 for(const state of result.states){const map=await open.api(`/api/runs/${result.id}/${state.code}/map`);assert.equal(map.features.length,Object.keys(project.assignments[state.code]).length);assert.ok(map.features.every(f=>f.properties.district===project.assignments[state.code][f.properties.geoid]));maps++;if(!state.metrics.balance_passed)balanceMisses++;if(!state.metrics.contiguous)disconnected++;}
 for(const mutate of[p=>p.experiment.states[0].metrics.multiscale_evidence.alpha=.4,p=>p.experiment.states[0].metrics.multiscale_evidence.graph_sha256='0'.repeat(64),p=>p.experiment.config.multiscale.total_steps++,p=>p.experiment.states[0].metrics.graph_boundary_m++,p=>p.experiment.config.seed='42']){const bad=structuredClone(project);mutate(bad);await assert.rejects(open.restoreProject(bad));assert.equal(open.jobs.size,jobsAfterOpen);rejected++;}
 if(c.multiscale.fine_level==='bg')for(const mutate of[p=>{let coordinates=p.experiment.config.multiscale.inputs[c.states[0]].geometry.features[0].geometry.coordinates;while(typeof coordinates[0][0]!=='number')coordinates=coordinates[0];coordinates[1][0]+=.0001;},p=>p.experiment.config.multiscale.inputs[c.states[0]].boundary_edges[0][2]++,p=>delete p.experiment.config.multiscale.inputs[c.states[0]],p=>p.experiment.config.multiscale.inputs[c.states[0]].graph.population[0]++]){const bad=structuredClone(project);mutate(bad);await assert.rejects(open.restoreProject(bad));assert.equal(open.jobs.size,jobsAfterOpen);rejected++;}
 await fs.writeFile(`target/multiscale-${c.mode}-${c.multiscale.fine_level}-${c.multiscale.coarse_level}-${c.search}-${c.steps}-${c.states.join('-')}.bisect`,JSON.stringify(project));return project;
}
for(const[fine,coarse]of[['tract','county'],['bg','tract'],['bg','county']])for(const adaptive of[false,true])for(const steps of[0,10])await check(config(fine,coarse,adaptive,steps));
for(const[fine,coarse]of[['tract','county'],['bg','tract'],['bg','county']])for(const adaptive of[false,true])await check(config(fine,coarse,adaptive,10,['AL','AK','RI']));
const realFetcher=async ref=>{const bytes=await fs.readFile(path.join(root,ref));return{ok:true,arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.length)};};
original.catalog.search_compatibility['standard-bisect'].push('multiscale','multiscale-adaptive');
for(const code of ['RI','IA','NC'])for(const adaptive of[false,true]){const c=config('tract','county',adaptive,5,[code]);c.name=`Real ${code} tract multiscale test`;c.districts=2;await check(c,original,realFetcher);}
const realGraph=JSON.parse(await fs.readFile(path.join(root,original.graphs['RI:2020'].graph_ref),'utf8')),realGeometry=JSON.parse(await fs.readFile(path.join(root,original.geometries['RI:2020']),'utf8'));
const fine={schema_version:'bisect-block-group-graph-v1',state:'RI',year:'2020',geoids:realGraph.geoids.flatMap(id=>[id+'1',id+'2']),population:realGraph.population.flatMap(p=>[Math.floor(p/2),p-Math.floor(p/2)]),adjacency:Array.from({length:realGraph.geoids.length*2},(_,i)=>[i^1,...realGraph.adjacency[Math.floor(i/2)].map(j=>j*2+i%2)].sort((a,b)=>a-b))},shapes=new Map(realGeometry.features.map(f=>[f.properties.geoid,f.geometry]));
const realFine=validateMultiscaleBundle({schema_version:'bisect-multiscale-input-v1',source_label:'SYNTHETIC fine units, boundaries and duplicated tract geometry for RI testing',graph:fine,boundary_edges:fine.adjacency.flatMap((ns,i)=>ns.filter(j=>j>i).map(j=>[i,j,100])),geometry:{type:'FeatureCollection',features:fine.geoids.map(id=>({type:'Feature',properties:{geoid:id},geometry:structuredClone(shapes.get(id.slice(0,11)))}))}},realGraph);
await fs.writeFile('target/RI-SYNTHETIC-realgraph-multiscale.json',JSON.stringify(realFine));
const browserConfig=config('bg','tract',true,10,['RI']);browserConfig.name='SYNTHETIC RI fine graph/map test';browserConfig.districts=2;browserConfig.balance_tolerance=.5;browserConfig.multiscale.inputs.RI=realFine;
await fs.writeFile('target/multiscale-browser-fine-project.bisect',JSON.stringify(await check(browserConfig,original,realFetcher)));
await fs.writeFile('target/multiscale-project-verification.json',JSON.stringify({engine_runs:runs,native_exact:native,restored_projects:restored,state_maps:maps,tamper_rejections:rejected,balance_misses:balanceMisses,disconnected,no_generation_on_open:true,scope:'synthetic tract/BG state-national cases plus six real RI/IA/NC tract cases and one explicitly synthetic RI fine bundle'},null,2)+'\n');
console.log(`Multiscale laboratory: ${restored} state/national project roundtrips, ${maps} maps, ${native} native replays, ${rejected} tamper rejections; ${balanceMisses} balance misses, ${disconnected} disconnected.`);
