import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {instantiateEngine} from '../../web/lab/wasm-engine.js';
import {WasmCatalog} from '../../web/lab/wasm-catalog.js';
import {createLabProject,parseLabProject,validateLabConfig} from '../../web/lab/laboratory-project.js';
import {isMultiscale,multiscaleRequest} from '../../web/lab/multiscale-input.js';
const root=process.argv[2];assert.ok(root,'Usage: test_one_district_wasm.mjs <catalog directory>');
const manifest=JSON.parse(await fs.readFile(path.join(root,'catalog.json'),'utf8'));
const fetcher=async ref=>{const bytes=await fs.readFile(path.join(root,ref));return{ok:true,arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.length)};};
const engine=await instantiateEngine(await fs.readFile(path.join(root,'bisect_wasm.wasm')));let executions=0;
class Worker {postMessage(message){setImmediate(()=>{if(this.terminated)return;try{if(message.type==='initialize')this.onmessage({data:{type:'ready'}});else{executions++;this.onmessage({data:{type:'result',id:message.id,result:engine.execute(message.request),memoryBytes:engine.memoryBytes()}});}}catch(error){this.onmessage({data:{type:'error',id:message.id,error:error.message}});}});}terminate(){this.terminated=true;}}
const lab=new WasmCatalog(manifest,fetcher,()=>new Worker()),restorer=new WasmCatalog(manifest,fetcher,()=>{throw new Error('Open must not start an engine.');});
const states=Object.keys(manifest.graphs).filter(key=>key.endsWith(':2020')).map(key=>key.slice(0,2));assert.ok(states.length);
const base={name:'One district matrix',mode:'state',states:[],year:'2020',chamber:'congressional',districts:1,structure:'standard-bisect',weights:'geographic',search:'single',seed:42,seeds:8,steps:20,percentile:0,alpha_county:0,balance_tolerance:.5,area_swing:1.1,iterations:10,timeout_seconds:30};
function required(structure,search){return {...(structure==='simulated-annealing'?{sa_steps_per_tract:10,sa_t0_factor:.01,sa_t_final:.0001}:{}),...(search==='smc-percentile'?{smc_particles:8,smc_resample_threshold:.5}:{})};}
function extra(structure,search){return {...(structure==='centroidal-voronoi'?{cvd_iters:20,cvd_metric:'graph-distance'}:{}),...(structure==='moving-knife'?{mka_orientations:180,mka_metric:'polsby'}:{}),...(structure==='compact-polsby'?{compact_epsilon:.2}:{}),...(structure==='ratio-optimal-area'?{area_init:'moving-knife'}:{}),...(structure==='flow-construction'?{flow_repair:'none'}:{}),...(search.startsWith('short-burst')?{burst_length:7,n_bursts:6}:{}),...(search==='parallel-tempering'?{pt_replicas:3,pt_swap_interval:4,pt_cold_tol:.005,pt_hot_tol:.05,seeds:0}:{})};}
let cases=0,rejected=0;const results=[];
for(const code of states)for(const structure of manifest.catalog.structures)for(const search of manifest.catalog.search_compatibility[structure])for(const weights of ['geographic','unweighted','county'])for(const profile of [0,...(Object.keys(extra(structure,search)).length?[1]:[])]) {
 if(isMultiscale(search)&&weights!=='geographic')continue; // Multiscale supports geographic weights only.
 const inputGraph=JSON.parse(await fs.readFile(path.join(root,manifest.graphs[`${code}:2020`].graph_ref),'utf8'));
 const demographics={schema_version:'bisect-demographic-fractions-v1',state:code,year:'2020',basis:'total-population',source_label:'Synthetic regression data',minority_fractions:Object.fromEntries(inputGraph.geoids.map(id=>[id,0.5]))};
 const proportional=['proportional-bisect','proportional-section'].includes(structure);
 const elections={schema_version:'bisect-election-counts-v1',state:code,year:'2020',election_year:'2016',source_label:'SYNTHETIC one-district regression counts',counts:Object.fromEntries(inputGraph.geoids.map((id,i)=>[id,{democratic:inputGraph.population[i]/2,two_party:inputGraph.population[i]}]))};
 const config={...(structure==='ratio-optimal-vra'?{w_vra:0.4,demographics:{[code]:demographics}}:{}),...(search==='vra-recom'?{vra_threshold:0.5,demographics:{[code]:demographics}}:{}),...base,states:[code],structure,search,weights,alpha_county:weights==='county'?3:0,...required(structure,search),...(profile?extra(structure,search):{}),...(proportional?{elections:{[code]:elections},...(structure==='proportional-section'?{proportional_eta:1.1}:{})}:{}),...(isMultiscale(search)?{steps:0,seeds:1,multiscale:{fine_level:'tract',coarse_level:'county',total_steps:0,alpha:.3,percentile:0,adaptive:search==='multiscale-adaptive'?{target_accept:.3,adapt_interval:5,gamma_0:.1,coarse_tol_factor:3}:null,inputs:{}}}:{})};
 const natural=manifest.catalog.states.find(state=>state.code===code)?.years.find(year=>year.year==='2020')?.districts.congressional===1;if(natural)config.districts=null;validateLabConfig(config);
 const job=lab.submit(config);while(lab.active)await new Promise(resolve=>setTimeout(resolve,1));const completed=await lab.api(`/api/runs/${job.id}`);assert.equal(completed.status,'completed',JSON.stringify(completed.logs));const state=completed.states[0];assert.equal(state.metrics.district_count,1);assert.equal(state.metrics.root_split,null);assert.equal(state.metrics.structure_evidence,null);assert.equal(state.metrics.max_deviation_percent,0);assert.ok(state.metrics.graph_boundary_m===0);assert.ok(state.metrics.weighted_boundary===0);assert.equal(state.metrics.contiguous,true);
 const project=await createLabProject(lab,job.id);parseLabProject(JSON.stringify(project));const graph=JSON.parse(await fs.readFile(path.join(root,manifest.graphs[`${code}:2020`].graph_ref),'utf8'));assert.ok(Object.values(project.assignments[code]).every(d=>d===1));assert.equal(Object.keys(project.assignments[code]).length,graph.geoids.length);
 const request=isMultiscale(search)?multiscaleRequest(graph,state.metrics.requested_options,config):{graph,options:state.metrics.requested_options,...((search==='vra-recom'||structure==='ratio-optimal-vra')?{demographics}:{}),...(proportional?{elections}:{})},file='target/one-district-native-request.json';await fs.writeFile(file,JSON.stringify(request));const native=spawnSync(`target/release/examples/${isMultiscale(search)?'execute_tool_request':'execute_request'}.exe`,[file],{encoding:'utf8',maxBuffer:16*1024*1024});assert.equal(native.status,0,native.stderr);assert.deepEqual(JSON.parse(native.stdout).assignments,project.assignments[code]);
 const before=executions,opened=await restorer.restoreProject(project);assert.equal(executions,before);assert.equal(restorer.worker,null);assert.deepEqual(opened.config,config);const map=await restorer.api(`/api/runs/${opened.id}/${code}/map`);assert.equal(map.features.length,graph.geoids.length);assert.ok(map.features.every(f=>f.properties.district===1));
 const reopened=await createLabProject(restorer,opened.id);assert.deepEqual(reopened.assignments,project.assignments);
 for(const field of ['structure_evidence','root_split']){const bad=structuredClone(project);bad.experiment.states[0].metrics[field]={method:'fabricated'};const priorJobs=restorer.jobs.size,priorOutputs=restorer.outputs.size;await assert.rejects(restorer.restoreProject(bad),isMultiscale(search)?/Multiscale projects must not claim|Invalid project root split/:/One-district project/);assert.equal(restorer.jobs.size,priorJobs);assert.equal(restorer.outputs.size,priorOutputs);rejected++;}
 const bad=structuredClone(project);bad.experiment.states[0].metrics.population++;await assert.rejects(restorer.restoreProject(bad),/metrics disagree/);rejected++;
 cases++;results.push({state:code,structure,search,weights,profile:profile?'explicit':'legacy',natural_one_seat:natural,units:graph.geoids.length});
}
await fs.writeFile('target/one-district-project-matrix.json',JSON.stringify({cases,native_wasm_assignment_matches:cases,save_open_map_roundtrips:cases,tampered_project_rejections:rejected,engine_executed_on_open:false,results},null,2));
console.log(`One district: ${cases} exact native/WASM assignment cases and Save/Open/map roundtrips across all supported structures/searches, legacy/explicit options and three weights; ${rejected} tampered projects rejected. Open executed no engine.`);
