import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {instantiateEngine} from '../../web/lab/wasm-engine.js';
import {WasmCatalog} from '../../web/lab/wasm-catalog.js';
import {createLabProject} from '../../web/lab/laboratory-project.js';
import {parseProject,createProject} from '../../web/lab/project.js';
const root=process.argv[2]||'dist/wasm-audit-handoff';
const year=process.argv[3]||'2020';
const manifest=JSON.parse(await fs.readFile(path.join(root,'catalog.json'),'utf8'));
const engine=await instantiateEngine(await fs.readFile(path.join(root,'bisect_wasm.wasm')));
const fetcher=async name=>{const bytes=await fs.readFile(path.join(root,name));return {ok:true,arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.length)};};
let operations=[];
class Worker {postMessage(m){setImmediate(()=>{if(this.terminated)return;try{if(m.type==='initialize')this.onmessage({data:{type:'ready'}});else{operations.push(m.request.operation||'generation');this.onmessage({data:{type:'result',id:m.id,result:engine.execute(m.request)}});}}catch(e){this.onmessage({data:{type:'error',id:m.id,error:e.message}});}});}terminate(){this.terminated=true;}}
const lab=new WasmCatalog(manifest,fetcher,()=>new Worker());
const states=Object.keys(manifest.graphs).filter(k=>k.endsWith(`:${year}`)).map(k=>k.split(':')[0]).slice(0,3);
const config={name:'Portable audit handoff',mode:'national',states,year,chamber:'congressional',districts:null,structure:'standard-bisect',weights:'county',search:'single',seed:42,seeds:2,steps:20,percentile:0,alpha_county:2,balance_tolerance:5,area_swing:1.1,iterations:10,timeout_seconds:60};
await assert.rejects(lab.exportPractitionerProject('absent',states[0]),/completed/);
const run=lab.submit(config);
await assert.rejects(lab.exportPractitionerProject(run.id,states[0]),/active/);
while(lab.active)await new Promise(r=>setTimeout(r,10));
const job=lab.jobs.get(run.id);assert.equal(job.status,'completed');
let checked=0;
for(const code of states){
  const pending=lab.exportPractitionerProject(run.id,code);
  assert.throws(()=>lab.submit(config),/export/);
  await assert.rejects(lab.exportPractitionerProject(run.id,code),/active/);
  const {exported,project}=await pending;
  const before=operations.length,opened=parseProject(JSON.stringify(project));assert.equal(operations.length,before);
  assert.deepEqual(opened.files,{plan:exported.document,context:exported.context});assert.equal(opened.files.profile,undefined);assert.equal(opened.result,null);
  await fs.writeFile(`target/audit-handoff-${code}-prepared.bisect`,JSON.stringify(project));
  const nativePath=`target/audit-handoff-${code}.json`;
  const original=JSON.parse(await fs.readFile('crates/rplan-audit/fixtures/grid3x3-valid-certificate.json','utf8'));
  const profile={...original.legal_profile,year:Number(year),jurisdiction:code,contiguity_required:true,nesting_rule:{type:'not-evaluated'},population_tolerance:{type:'exact-ppm',max_deviation_ppm:50000}};
  const audit={operation:'audit-plan',plan:opened.files.plan.plan,context:opened.files.context,profile,constraints:opened.constraints,generated_at_utc:'2026-10-04T00:00:00Z',lineage:null};
  await fs.writeFile(nativePath,JSON.stringify(audit));
  const cert=engine.execute(audit),native=JSON.parse(execFileSync('target/release/examples/execute_tool_request.exe',[nativePath],{encoding:'utf8'}));assert.deepEqual(cert,native);assert.equal(cert.result,'pass');
  const completed=createProject({...opened,files:{...opened.files,profile,certificate:cert},operation:'audit-plan',result:cert,lastOperation:'audit-plan'});
  const restored=parseProject(JSON.stringify(completed));engine.execute({operation:'verify-certificate',certificate:restored.result,plan:restored.files.plan.plan,context:restored.files.context});
  await fs.writeFile(`target/audit-handoff-${code}.bisect`,JSON.stringify(completed));checked++;
  assert.ok(!lab.assets.has(manifest.graphs[`${code}:${year}`].graph_ref));
}
const saved=await createLabProject(lab,run.id),restoredLab=new WasmCatalog(manifest,fetcher,()=>new Worker());
const count=operations.length,restored=await restoredLab.restoreProject(saved);assert.equal(operations.length,count);
const fromImported=await restoredLab.exportPractitionerProject(restored.id,states[0]);assert.deepEqual(fromImported.exported.document.plan.assignment,(await lab.exportPractitionerProject(run.id,states[0])).exported.document.plan.assignment);
const victim=lab.outputs.get(`${run.id}:${states[0]}`),id=Object.keys(victim)[0],prior=victim[id];victim[id]=0;
const before=operations.length;await assert.rejects(lab.exportPractitionerProject(run.id,states[0]));assert.equal(operations.length,before);victim[id]=prior;assert.equal(lab.exporting,false);
await fs.writeFile('target/audit-handoff-verification.json',JSON.stringify({states:checked,native_audit_parity:true,certificate_roundtrip:true,imported_lab_export:true,atomic_concurrency_and_tamper_rejection:true,no_implicit_profile_or_audit:true},null,2));
console.log(`Audit handoff: ${checked} real states generated/exported/audited with exact native certificate parity; project reopen/verification, imported lab export, explicit profile, concurrency and assignment tamper guards passed.`);
