#!/usr/bin/env python3
"""Manage repo-map.toml and generated Cargo local dependency overrides."""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python < 3.11 fallback
    print("Python 3.11+ is required for tomllib", file=sys.stderr)
    sys.exit(2)


ROOT = Path(__file__).resolve().parents[1]
MAP_PATH = ROOT / "repo-map.toml"


def _load_map() -> dict:
    with MAP_PATH.open("rb") as handle:
        return tomllib.load(handle)


def _repo_root(repo: dict) -> Path:
    if "absolute" in repo:
        return Path(repo["absolute"]).expanduser()
    if "relative" not in repo:
        raise ValueError("repo entry must define either 'relative' or 'absolute'")
    return (ROOT / repo["relative"]).resolve()


def _display_path(path: Path) -> str:
    return os.path.relpath(path, ROOT)


def _toml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _cargo_patch_rows(repo_map: dict) -> list[tuple[str, str, Path]]:
    rows: list[tuple[str, str, Path]] = []
    for name, repo in sorted(repo_map.get("repos", {}).items()):
        repo_root = _repo_root(repo)
        for patch in repo.get("cargo_patches", []):
            package = patch["package"]
            source = patch["source"]
            patch_path = (repo_root / patch.get("path", ".")).resolve()
            rows.append((source, package, patch_path))
    return rows


def render_cargo_config(repo_map: dict) -> str:
    by_source: dict[str, list[tuple[str, Path]]] = {}
    for source, package, path in _cargo_patch_rows(repo_map):
        by_source.setdefault(source, []).append((package, path))

    lines = [
        "# Generated by tools/repo_map.py from repo-map.toml.",
        "# Do not edit by hand; update repo-map.toml and regenerate.",
        "",
    ]
    for source in sorted(by_source):
        lines.append(f'[patch."{source}"]')
        for package, path in sorted(by_source[source]):
            lines.append(f"{package} = {{ path = {_toml_string(_display_path(path))} }}")
        lines.append("")
    return "\n".join(lines)


def cargo_config_path(repo_map: dict) -> Path:
    rel = repo_map.get("standard", {}).get("cargo_config", ".cargo/config.toml")
    return ROOT / rel


def write_cargo_config(_: argparse.Namespace) -> int:
    repo_map = _load_map()
    path = cargo_config_path(repo_map)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_cargo_config(repo_map), encoding="utf-8")
    print(f"wrote {_display_path(path)}")
    return 0


def check(_: argparse.Namespace) -> int:
    repo_map = _load_map()
    errors: list[str] = []

    for name, repo in sorted(repo_map.get("repos", {}).items()):
        root = _repo_root(repo)
        if not root.exists():
            errors.append(f"missing repo {name}: {_display_path(root)}")
        for patch in repo.get("cargo_patches", []):
            patch_path = root / patch.get("path", ".")
            if not patch_path.exists():
                errors.append(
                    f"missing cargo patch path {name}.{patch['package']}: "
                    f"{_display_path(patch_path)}"
                )

    expected = render_cargo_config(repo_map)
    config_path = cargo_config_path(repo_map)
    if not config_path.exists():
        errors.append(f"missing generated Cargo config: {_display_path(config_path)}")
    elif config_path.read_text(encoding="utf-8") != expected:
        errors.append(
            f"stale generated Cargo config: run 'python tools/repo_map.py write-cargo-config'"
        )

    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print("repo-map check: pass")
    return 0


def list_repos(_: argparse.Namespace) -> int:
    repo_map = _load_map()
    for name, repo in sorted(repo_map.get("repos", {}).items()):
        root = _repo_root(repo)
        status = "present" if root.exists() else "missing"
        clone_url = repo.get("clone_url", repo.get("canonical", ""))
        branch = repo.get("branch")
        suffix = f" ({branch})" if branch else ""
        print(f"{name}: {status} {_display_path(root)} <- {clone_url}{suffix}")
    return 0


def clone_commands(_: argparse.Namespace) -> int:
    repo_map = _load_map()
    for name, repo in sorted(repo_map.get("repos", {}).items()):
        if name == "bisect":
            continue
        root = _repo_root(repo)
        if root.exists():
            continue
        clone_url = repo.get("clone_url")
        if not clone_url:
            continue
        branch = repo.get("branch")
        branch_arg = f" --branch {branch}" if branch else ""
        print(f"git clone{branch_arg} {clone_url} {_display_path(root)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("write-cargo-config", help="generate .cargo/config.toml from repo-map.toml").set_defaults(
        func=write_cargo_config
    )
    sub.add_parser("check", help="validate mapped paths and generated Cargo config").set_defaults(
        func=check
    )
    sub.add_parser("list", help="list mapped repositories and local status").set_defaults(
        func=list_repos
    )
    sub.add_parser("clone-commands", help="print git clone commands for missing mapped repos").set_defaults(
        func=clone_commands
    )

    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
