#!/usr/bin/env python3
"""Inventory 50-State 2020 block sources and connected RCTX readiness."""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

import pyogrio


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts"))
from state_config import STATE_CONFIG_2020  # noqa: E402


FIPS = {
    "AL": "01", "AK": "02", "AZ": "04", "AR": "05", "CA": "06",
    "CO": "08", "CT": "09", "DE": "10", "FL": "12", "GA": "13",
    "HI": "15", "ID": "16", "IL": "17", "IN": "18", "IA": "19",
    "KS": "20", "KY": "21", "LA": "22", "ME": "23", "MD": "24",
    "MA": "25", "MI": "26", "MN": "27", "MS": "28", "MO": "29",
    "MT": "30", "NE": "31", "NV": "32", "NH": "33", "NJ": "34",
    "NM": "35", "NY": "36", "NC": "37", "ND": "38", "OH": "39",
    "OK": "40", "OR": "41", "PA": "42", "RI": "44", "SC": "45",
    "SD": "46", "TN": "47", "TX": "48", "UT": "49", "VT": "50",
    "VA": "51", "WA": "53", "WV": "54", "WI": "55", "WY": "56",
}
SCRIPT = Path("scripts/research/inventory_national_2020.py")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> None:
    rows = []
    existing_bytes_per_unit = []
    for code, config in sorted(STATE_CONFIG_2020.items()):
        fips = FIPS[code]
        lower = code.lower()
        shape = (
            ROOT / f"data/2020/tiger/blocks/tl_2020_{fips}_tabblock20/"
            f"tl_2020_{fips}_tabblock20.shp"
        )
        pl_dir = ROOT / f"data/2020/redistricting/{lower}2020.pl"
        geo = pl_dir / f"{lower}geo2020.pl"
        pop = pl_dir / f"{lower}000012020.pl"
        rctx = ROOT / f"data/2020/certified/{lower}_blocks_2020.rctx"
        block_count = int(pyogrio.read_info(shape)["features"]) if shape.is_file() else None
        if rctx.is_file() and block_count:
            existing_bytes_per_unit.append(rctx.stat().st_size / block_count)
        rows.append(
            {
                "state": code,
                "name": config["name"],
                "fips": fips,
                "districts": config["districts"],
                "block_count": block_count,
                "tiger_ready": all(
                    shape.with_suffix(suffix).is_file()
                    for suffix in (".shp", ".dbf", ".shx")
                ),
                "pl_geo_ready": geo.is_file(),
                "pl_population_ready": pop.is_file(),
                "rctx_ready": rctx.is_file(),
                "rctx_bytes": rctx.stat().st_size if rctx.is_file() else None,
            }
        )
    bytes_per_unit = (
        sum(existing_bytes_per_unit) / len(existing_bytes_per_unit)
        if existing_bytes_per_unit
        else 300
    )
    missing_sources = [
        row["state"]
        for row in rows
        if not (
            row["tiger_ready"]
            and row["pl_geo_ready"]
            and row["pl_population_ready"]
        )
    ]
    report = {
        "schema_version": "certified-national-2020-inventory-v1",
        "status": "ready" if not missing_sources else "blocked",
        "state_count": len(rows),
        "district_count": sum(row["districts"] for row in rows),
        "total_blocks": sum(row["block_count"] or 0 for row in rows),
        "source_ready_states": len(rows) - len(missing_sources),
        "existing_rctx_states": sum(row["rctx_ready"] for row in rows),
        "missing_source_states": missing_sources,
        "estimated_rctx_bytes": round(
            bytes_per_unit * sum(row["block_count"] or 0 for row in rows)
        ),
        "estimated_rctx_gib": round(
            bytes_per_unit * sum(row["block_count"] or 0 for row in rows) / 2**30,
            2,
        ),
        "states": sorted(
            rows, key=lambda row: (row["districts"], row["block_count"] or 10**9)
        ),
        "batch_order": [
            row["state"]
            for row in sorted(
                rows, key=lambda row: (row["block_count"] or 10**9, row["state"])
            )
            if not row["rctx_ready"]
        ],
        "claim_boundary": "Local source and context readiness inventory; no State package is generated by this report.",
    }
    out = ROOT / "docs/experiments/nationwide-2020"
    out.mkdir(parents=True, exist_ok=True)
    report_path = out / "inventory.json"
    report_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    manifest = {
        "schema_version": "certified-national-2020-inventory-package-v1",
        "package_id": "nationwide-2020-inventory",
        "status": report["status"],
        "files": [{"path": report_path.name, "sha256": sha256(report_path)}],
        "builder_path": SCRIPT.as_posix(),
        "builder_sha256": sha256(ROOT / SCRIPT),
        "claim_boundary": report["claim_boundary"],
    }
    (out / "manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )
    print(
        f"Nationwide inventory: {report['source_ready_states']}/50 sources, "
        f"{report['existing_rctx_states']} RCTX, {report['total_blocks']} blocks, "
        f"{report['estimated_rctx_gib']} GiB estimated"
    )


if __name__ == "__main__":
    main()
